name: Build BennuGD2 for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:   
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSYS2
        run: |
          choco install msys2 --no-progress
          refreshenv

      - name: Set up MSYS2
        run: |
          C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syuu"
          C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S \
            mingw-w64-x86_64-SDL2 \
            mingw-w64-x86_64-SDL2_image \
            mingw-w64-x86_64-SDL2_mixer \
            mingw-w64-x86_64-cmake \
            mingw-w64-x86_64-flac \
            mingw-w64-x86_64-freetype \
            mingw-w64-x86_64-gcc \
            mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-libmikmod \
            mingw-w64-x86_64-libmodplug \
            mingw-w64-x86_64-libogg \
            mingw-w64-x86_64-libpng \
            mingw-w64-x86_64-libtheora \
            mingw-w64-x86_64-libvorbis \
            mingw-w64-x86_64-libwebp \
            mingw-w64-x86_64-ninja \
            mingw-w64-x86_64-openal \
            mingw-w64-x86_64-sqlite3"

      - name: Clone BennuGD2 repository
        run: git clone https://github.com/SplinterGU/BennuGD2.git

      - name: Initialize submodules
        run: |
          cd BennuGD2/
          git submodule update --init --recursive

      - name: Build SDL GPU for Windows
        run: |
          cd BennuGD2/vendor
          C:\tools\msys64\usr\bin\bash.exe -lc "./build-sdl-gpu.sh windows"

      - name: Build BennuGD2 for Windows
        run: |
          cd BennuGD2/
          C:\tools\msys64\usr\bin\bash.exe -lc "./build.sh windows"
