name: Build and Deploy BennuGD2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la UI de GitHub

jobs:
  build-windows:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 build-essential cmake autoconf libtool pkg-config rar libz-mingw-w64-dev nasm

      - name: Build libogg for Windows
        run: |
          wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz
          tar -xvzf libogg-1.3.5.tar.gz
          cd libogg-1.3.5
          ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32
          make && sudo make install
          cd ..

      - name: Build libtheora for Windows
        run: |
          wget http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz
          tar -xvzf libtheora-1.1.1.tar.gz
          cd libtheora-1.1.1
          # Pasar la ruta correcta de libogg
          ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32 --with-ogg=/usr/x86_64-w64-mingw32 --disable-shared
          make && sudo make install
          cd ..

      - name: Build FFmpeg dependencies for Windows
        run: |
          # Descargar y compilar FFmpeg para Windows usando mingw-w64
          mkdir ffmpeg_build
          cd ffmpeg_build
          
          # Descargar el código fuente de FFmpeg
          wget https://ffmpeg.org/releases/ffmpeg-5.1.2.tar.bz2
          tar -xjf ffmpeg-5.1.2.tar.bz2
          cd ffmpeg-5.1.2
          
          # Configurar y compilar FFmpeg para Windows (x86_64-w64-mingw32)
          ./configure --prefix=/usr/x86_64-w64-mingw32 \
                      --target-os=mingw32 \
                      --arch=x86_64 \
                      --cross-prefix=x86_64-w64-mingw32- \
                      --enable-shared \
                      --disable-static \
                      --enable-gpl \
                      --enable-version3 \
                      --enable-libvorbis \
                      --enable-libtheora \
                      --enable-libvpx \
                      --extra-cflags="-I/usr/x86_64-w64-mingw32/include" \
                      --extra-ldflags="-L/usr/x86_64-w64-mingw32/lib"
          make && sudo make install
          cd ../..

      - name: Build dependencies
        run: |
          cd vendor
          cd SDL2-2.28.4
          sed -i 's,/usr/local,/usr,g' Makefile
          sudo make cross
          cd ..
          cd SDL2_mixer-2.6.3
          sed -i 's,/usr/local,/usr,g' Makefile
          sudo make cross
          cd ..
          cd SDL2_image-2.6.3
          sed -i 's,/usr/local,/usr,g' Makefile
          sudo make cross
          cd ..

      - name: Update submodules and Build
        run: |
          git submodule update --init --recursive
          cd vendor
          ./build-sdl-gpu.sh windows
          cd ..
          ./build.sh windows
          echo "#### Building package ####"
          mkdir -p packages 2>/dev/null
          rm -f packages/*
          if [[ -d build/x86_64-w64-mingw32/bin ]]; then \
            rar a -ep1 packages/bgd2-x86_64-w64-mingw32-$(date +"%Y-%m-%d").rar \
                        build/x86_64-w64-mingw32/bin/*.exe \
                        build/x86_64-w64-mingw32/bin/*.dll \
                        dependencies/x86_64-w64-mingw32/libSDL2_gpu.dll \
                        /usr/x86_64-w64-mingw32/bin/libogg*.dll \
                        /usr/x86_64-w64-mingw32/bin/libvorbis*.dll \
                        /usr/x86_64-w64-mingw32/bin/SDL2.dll \
                        /usr/x86_64-w64-mingw32/bin/SDL2_image.dll \
                        /usr/x86_64-w64-mingw32/bin/SDL2_mixer.dll \
                        $(find /usr/x86_64-w64-mingw32 -name 'zlib1.dll') \
                        /usr/x86_64-w64-mingw32/lib/libwinpthread-*.dll \
                        WhatsNew.txt; \
          fi

      - name: Upload BennuGD2 artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BennuGD2-windows
          path: packages/bgd2-x86_64-w64-mingw32-*.rar
