name: Build for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite la ejecución manual del flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MinGW-w64 and dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libtheora-dev libvorbis-dev

      - name: Install SDL2 for MinGW
        run: |
          wget https://libsdl.org/release/SDL2-devel-2.28.1-mingw.zip
          unzip SDL2-devel-2.28.1-mingw.zip -d $HOME/SDL2
          export CMAKE_PREFIX_PATH=$HOME/SDL2/x86_64-w64-mingw32

      - name: Verify SDL2 installation
        run: |
          ls -R $HOME/SDL2

      - name: Clone BennuGD2 repository
        run: |
          git clone https://github.com/SplinterGU/BennuGD2.git
          cd BennuGD2/
          git submodule update --init --recursive

      - name: Build SDL GPU
        run: |
          cd BennuGD2/vendor/
          cmake .. -DCMAKE_PREFIX_PATH=$HOME/SDL2/x86_64-w64-mingw32 -DSDL2_INCLUDE_DIR=$HOME/SDL2/x86_64-w64-mingw32/include -DSDL2_LIBRARY=$HOME/SDL2/x86_64-w64-mingw32/lib/SDL2.dll
          ./build-sdl-gpu.sh windows

      - name: Build BennuGD2
        run: |
          cd BennuGD2
          ./build.sh windows clean

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BennuGD2-artifacts
          path: |
            BennuGD2/build/**
