name: Compilar BennuGD2

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Permite la ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libpng-dev libsdl2-dev git

      - name: Compilar BennuGD2
        run: |
          cd core
          make -j$(nproc)

      - name: Verificar compilación
        run: ./bgdi --version
