name: Build BennuGD for Windows

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-zlib
            ninja
          update: true

      - name: Fix old CMakeLists.txt in SDL_gpu
        run: |
          sed -i 's/cmake_minimum_required(VERSION 2.8)/cmake_minimum_required(VERSION 3.5)/' vendor/sdl-gpu/CMakeLists.txt

      - name: Build SDL_gpu
        run: ./build-sdl-gpu.sh

      - name: Build BennuGD
        run: ./build.sh windows

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bennugd-windows
          path: bin/windows/*
