name: Build BennuGD2
on:
  push:
    branches:
      - main  # Cambia esto por tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest  # Puedes cambiar el sistema operativo según tus necesidades

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake and necessary dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential  # Instala CMake y otras dependencias necesarias

      - name: Run build.sh
        run: ./build.sh windows   # Ejecuta tu script de construcción, que a su vez ejecuta CMake

      # Puedes agregar más pasos aquí según sea necesario, como pruebas, empaquetado, etc. 
