name: Build BennuGD2 for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Necesario para publicar artefactos

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_gfx
            mingw-w64-x86_64-libtheora

      - name: Build BennuGD2 (Windows)
        shell: msys2 {0}
        run: |
          git submodule update --init --recursive
          cd vendor
          ./build-sdl-gpu.sh windows
          cd ..
          ./build.sh windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BennuGD2-Windows
          path: BennuGD2/build/mingw-w64/bin/
